const babyAttributes = {
  background: [
    { name: 'antarctica', start: 0, end: 69 },
    { name: 'beach', start: 70, end: 119 },
    { name: 'yellow', start: 120, end: 149 },
    { name: 'beach2', start: 150, end: 189 },
    { name: 'green', start: 190, end: 239 },
    { name: 'blue', start: 240, end: 279 },
    { name: 'city', start: 280, end: 313 },
    { name: 'desert', start: 314, end: 363 },
    { name: 'heaven', start: 364, end: 403 },
    { name: 'icecave', start: 404, end: 433 },
    { name: 'jungle', start: 434, end: 473 },
    { name: 'mountain', start: 474, end: 483 },
    { name: 'oasis', start: 484, end: 513 },
    { name: 'oceania', start: 514, end: 538 },
    { name: 'pacific', start: 539, end: 558 },
    { name: 'purple', start: 559, end: 593 },
    { name: 'rainbow', start: 594, end: 633 },
    { name: 'red', start: 634, end: 683 },
    { name: 'space', start: 684, end: 743 },
    { name: 'split', start: 744, end: 783 },
    { name: 'split2', start: 784, end: 823 },
    { name: 'split3', start: 824, end: 863 },
    { name: 'swamp', start: 864, end: 903 },
    { name: 'underwater', start: 904, end: 913 },
    { name: 'underwater2', start: 914, end: 919 },
    { name: 'vulcano', start: 920, end: 999 },
  ],
  base: [
    'aqua',
    'crystal',
    'desert',
    'terra',
  ],
  standardBase: [
    'base',
    'wood',
    'gold',
    'goldstone',
    'gummybear',
    'ice',
    'lava',
    'radioactive',
    'rock'
  ],
  eyes: [
    { name: 'basic', start: 0, end: 9 },
    { name: 'angry', start: 10, end: 89 },
    { name: 'sleepy', start: 90, end: 99 }
  ],
  mouth: [
    { name: 'basic', start: 0, end: 32 },
    { name: 'blow', start: 33, end: 65 },
    { name: 'open', start: 66, end: 99 }
  ],
  glasses: [
    { name : 'empty' , start : 0, end : 24 },
    { name : 'grandpa' , start : 25, end : 44 },
    { name : 'stevejobs' , start : 45, end : 74 },
    { name : 'sunglasses' , start : 75, end : 99 },
  ],
  hat: [
    { name: 'empty', start: 0, end: 259 },
    { name: 'academy', start: 260, end: 303 },
    { name: 'bandana', start: 304, end: 350 },
    { name: 'baseball', start: 351, end: 392 },
    { name: 'baseball solana', start: 393, end: 434 },
    { name: 'captain', start: 435, end: 484 },
    { name: 'chinese', start: 485, end: 526 },
    { name: 'cowboy', start: 527, end: 573 },
    { name: 'crown', start: 574, end: 593 },
    { name: 'cylinder', start: 594, end: 639 },
    { name: 'fastfood', start: 640, end: 681 },
    { name: 'gloriole', start: 682, end: 723 },
    { name: 'helmet', start: 724, end: 768 },
    { name: 'japan', start: 769, end: 810 },
    { name: 'party', start: 811, end: 852 },
    { name: 'santa', start: 853, end: 893 },
    { name: 'smallhat', start: 894, end: 937 },
    { name: 'squid', start: 938, end: 974 },
    { name: 'wizard', start: 975, end: 999 }
  ],
  outfit: [
    { name: 'empty', start: 0, end: 40 },
    { name: 'fastfood', start: 41, end: 57 },
    { name: 'football', start: 58, end: 74 },
    { name: 'suitandtie', start: 75, end: 82 },
    { name: 'turtleneck', start: 83, end: 99 }
  ],
  fire: [
    { name: 'empty', start: 0, end: 29 },
    { name: '01', start: 30, end: 36 },
    { name: '02', start: 37, end: 43 },
    { name: '03', start: 44, end: 50 },
    { name: '04', start: 51, end: 57 },
    { name: '05', start: 58, end: 64 },
    { name: '06', start: 65, end: 71 },
    { name: '07', start: 72, end: 78 },
    { name: '08', start: 79, end: 85 },
    { name: '09', start: 86, end: 92 },
    { name: '10', start: 93, end: 99 }
  ],
  extraHand: [
    { name: 'beer', start: 0, end: 17 },
    { name: 'machete', start: 18, end: 37 },
    { name: 'map', start: 38, end: 57 },
    { name: 'torch', start: 58, end: 77 },
    { name: 'trident', start: 78, end: 99 }
  ],
  extraHandFire: [
    '00',
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    'potion'
  ],
  extraLaserEyes: [
    'angry base',
    'basic base',
    'sleepy base',
    'angry aqua',
    'basic aqua',
    'sleepy aqua',
    'angry crystal',
    'basic crystal',
    'sleepy crystal',
    'angry desert',
    'basic desert',
    'sleepy desert',
    'angry terra',
    'basic terra',
    'sleepy terra'
  ],
  chain: [
    'empty',
    'base',
    'solana'
  ]
}

export default babyAttributes