const kingAttributes = {
  background: [
    { name: 'antarctica', start: 0, end: 7 },
    { name: 'beach', start: 8, end: 10 },
    { name: 'beach b', start: 11, end: 13 },
    { name: 'beach2', start: 14, end: 16 },
    { name: 'green', start: 17, end: 19 },
    { name :'blue', start: 20, end: 22 },
    { name: 'city', start: 23, end: 25 },
    { name: 'desert', start: 26, end: 28 },
    { name: 'heaven', start: 29, end: 31 },
    { name: 'icecave', start: 32, end: 39},
    { name: 'jungle', start: 40, end: 42 },
    { name: 'mountain', start: 43, end: 45 },
    { name: 'oasis', start: 46, end: 48 },
    { name: 'oceania', start: 49, end: 51 },
    { name: 'pacific', start: 52, end: 54 },
    { name: 'purple', start: 55, end: 57 },
    { name: 'rainbow', start: 58, end: 60 },
    { name: 'red', start: 61, end: 63 },
    { name: 'space', start: 64, end: 71 },
    { name: 'split',  start: 72, end: 73 },
    { name: 'split2', start: 74, end: 76 },
    { name: 'split3', start: 77, end: 79 },
    { name: 'swamp', start: 80, end: 82 },
    { name: 'underwater', start: 82, end: 84 },
    { name: 'underwater2', start: 85, end: 87 },
    { name: 'vulcano', start: 88, end: 95 }
  ],
  base: [
    'aqua',
    'crystal',
    'desert',
    'terra',
  ],
  standardBase: [
    'base',
    'metal',
    'snow',
    'stone',
    'wood',
  ],
  legendaryBase: [
    { name: 'cyber', start: 0, end: 13 },
    { name: 'gold', start: 14, end: 21 },
    { name: 'ice', start: 22, end: 27 },
    { name: 'lava', start: 28, end: 40 },
    { name: 'rock', start: 41, end: 49 }
  ],
  eyes: [
    { name: 'angry', start: 0, end: 79 },
    { name: 'basic', start: 80, end: 89 },
    { name: 'sleepy', start: 90, end: 99 }
  ],
  mouth: [
    { name: 'basic', start: 0, end: 32},
    { name: 'closed', start: 33, end: 65 },
    { name: 'open', start: 66, end: 99 }
  ],
  glasses: [
    { name: 'empty', start: 0, end: 24 },
    { name: 'grandpa', start: 25, end: 49 },
    { name: 'stevejobs', start: 50, end: 69 },
    { name: 'sunglasses', start: 70, end: 99 },
  ],
  hat: [
    { name: 'academy', start: 0, end: 3 },
    { name: 'bandana', start: 4, end: 6 },
    { name: 'baseball', start: 7, end: 10 },
    { name: 'baseball solana', start: 11, end: 18 },
    { name: 'captain', start: 19, end: 22 },
    { name:'chinese', start: 23, end: 26 },
    { name: 'cowboy', start: 27, end: 29 },
    { name: 'crown', start: 30, end: 31 },
    { name: 'cylinder', start: 32, end: 35 },
    { name: 'empty', start: 36, end: 61 },
    { name: 'fastfood', start: 62, end: 65 },
    { name: 'gloriole', start: 66, end: 69 },
    { name: 'helmet', start: 70, end: 73 },
    { name: 'japan', start: 74, end: 80 },
    { name: 'party', start: 81, end: 84 },
    { name:'santa', start:85, end: 88 },
    { name: 'smallhat', start: 89, end: 92 },
    { name: 'squid', start: 93, end: 95 },
    { name: 'wizard', start: 96, end:99 }
  ],
  outfit: [
    { name: 'empty', start: 0, end: 31 },
    { name: 'fastfood', start: 32, end: 49 },
    { name: 'football', start: 50, end: 64 },
    { name: 'suitandtie', start: 65, end: 83 },
    { name: 'turtleneck', start: 84, end: 99 }
  ],
  extraFireNose: [
    { name: '00', start: 0, end: 5 },
    { name: '01', start: 6, end: 13 },
    { name: '02', start: 14, end: 15 },
    { name: '03', start: 16, end: 19 },
    { name: '04', start: 20, end: 23 },
    { name: '05', start: 24, end: 31 },
    { name: '06', start: 32, end: 36 },
    { name: '07', start: 37, end: 42 },
    { name: '08', start: 43, end: 47 },
    { name: '09', start: 48, end: 53 },
    { name: '10', start: 54, end: 62 },
    { name: 'empty', start: 63, end: 96 },
  ],
  extraHand: [
    { name: 'beer', start: 0, end: 14 },
    { name: 'empty', start: 15, end: 24 },
    { name: 'machete', start: 25, end: 43 },
    { name: 'map', start: 44, end:57 },
    { name: 'neckle solana', start: 58, end: 67 },
    { name: 'neckle', start: 68, end: 77 },
    { name: 'potion', start: 78, end: 87 },
    { name: 'torch', start:88, end: 93 },
    { name: 'trident', start: 94, end: 99 },
    { name: 'viking', start: 100, end: 104 }
  ]
}

export default kingAttributes 