const teenageAttributes = {
  background: [
    { name: 'antarctica', start: 0, end: 7 },
    { name: 'beach', start: 8, end: 10},
    { name: 'yellow', start: 11, end: 13 },
    { name: 'beach2', start: 14, end: 16 },
    { name: 'green', start: 17, end: 19 },
    { name: 'blue', start : 20, end: 22 },
    { name: 'city', start: 23, end: 25 },
    { name: 'desert', start: 26, end: 28 },
    { name: 'green', start: 29, end: 31 },
    { name: 'heaven', start: 32, end: 34 },
    { name: 'icecave', start: 35, end: 42 },
    { name: 'jungle', start: 43, end: 45 },
    { name: 'mountain', start: 46, end: 48 },
    { name: 'oasis', start: 49, end: 51 },
    { name: 'oceania', start: 52, end: 54 },
    { name: 'pacific', start: 55, end: 57 },
    { name: 'purple', start: 58, end: 60 },
    { name: 'rainbow', start: 61, end: 63 },
    { name: 'red', start: 64, end: 66 },
    { name: 'space', start: 67, end: 74 },
    { name: 'split', start: 75, end: 77 },
    { name: 'split2', start: 78, end: 80 },
    { name: 'split3', start: 81, end: 83 },
    { name: 'swamp', start: 84, end: 86 },
    { name: 'underwater', start: 87, end: 89 },
    { name: 'underwater2', start: 90, end: 92 },
    { name: 'vulcano', start: 93, end: 99 }
  ],
  base: [
    'aqua',
    'crystal',
    'desert',
    'terra',
  ],
  standardBase: [
    'base',
    'fabric',
    'luxury',
    'rainbow',
    'stone',
    'wood',
  ],
  legendaryBase: [
    { name: 'gold', start: 0, end: 5 },
    { name: 'ice', start: 6, end: 10 },
    { name: 'lava', start: 11, end: 33 },
    { name: 'marble', start: 34, end: 44 },
    { name: 'rock', start: 45, end: 64 },
  ],
  eyes: [
    { name: 'angry', start: 0, end: 79 },
    { name: 'basic', start: 80, end: 89 },
    { name: 'sleepy', start: 90, end: 99 },
  ],
  mouth: [
    { name: 'basic', start: 0, end: 32 },
    { name: 'blow', start: 33, end: 65 },
    { name: 'open', start: 66, end: 99 }
  ],
  glasses: [
    { name: 'grandpa', start: 0, end: 14 },
    { name: 'stevejobs', start: 15, end: 34 },
    { name: 'sunglasses00', start: 35, end: 54 },
    { name: 'sunglasses01', start: 55, end: 74 },
    { name: 'empty', start: 75, end: 99 }
  ],
  hat: [
    { name: 'academy', start: 0, end: 3 },
    { name: 'bandana', start: 4, end: 6 },
    { name: 'baseball', start: 7, end: 10 },
    { name: 'baseball solana', start: 11, end: 18 },
    { name: 'captain', start: 19, end: 22 },
    { name: 'chinese', start: 23, end: 26 },
    { name: 'cowboy', start: 27, end: 29 },
    { name: 'crown', start: 30, end: 31 },
    { name: 'cylinder', start: 32, end: 35 },
    { name: 'empty', start: 36, end: 61 },
    { name: 'fastfood', start: 62, end: 65 },
    { name: 'gloriole', start: 66, end: 69 },
    { name: 'helmet', start: 70, end: 73 },
    { name: 'japan', start: 74, end: 80 },
    { name: 'party', start: 81, end: 84 },
    { name:'santa', start:85, end: 88 },
    { name: 'smallhat00', start: 89, end: 90 },
    { name: 'smallhat01', start: 91, end: 92 },
    { name: 'squid', start: 93, end: 95 },
    { name: 'wizard', start: 96, end:99 }
  ],
  outfit: [
    { name: 'fastfood', start: 0, end: 12 },
    { name: 'football', start: 13, end: 25 },
    { name: 'neckle', start: 26, end: 34 },
    { name: 'neckle_solana', start: 35, end: 50 },
    { name: 'suitandtie00', start: 51, end: 61 },
    { name: 'suitandtie01', start: 62, end: 68 }, 
    { name: 'suitandtie02', start: 69, end: 77 },
    { name: 'turtleneck', start: 78, end: 88 },
    { name: 'empty', start: 89, end: 99 }
  ],
  fire: [
    { name: '00', start: 0, end: 3 },
    { name: '01', start: 4, end: 7 },
    { name: '02', start: 8, end: 13 },
    { name: '03', start: 14, end: 17 },
    { name: '04', start: 18, end: 21 },
    { name: '05', start: 22, end: 27 },
    { name: '06', start: 28, end: 31 },
    { name: '07', start: 32, end: 35 },
    { name: '08', start: 36, end: 37 },
    { name: '09', start : 38, end: 39 },
    { name: '10', start: 40, end: 43 },
    { name: 'none', start: 44, end: 63 }
  ]
}

export default teenageAttributes